[package]
name = "gblib"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Plant <plant.ethan@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
