name: Build and Run Tests
on:
  push:
    branches: [main]
    paths:
      - "rustyboy/**"
      - "rustyboy-core/**"
  pull_request:
    branches: [main]
    paths:
      - "rustyboy/**"
      - "rustyboy-core/**"
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup update --no-self-update stable
      - name: Install Dependencies
        run: sudo apt install libsdl2-dev
      - name: Build
        run: cargo build --verbose
      - name: Run Tests
        run: cargo test --verbose
